name: Deploy to Docker Swarm

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t myapp:${{ github.sha }} .

      - name: Push Docker Image
        run: docker push myapp:${{ github.sha }}

      - name: SSH into Docker Swarm and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SWARM_HOST }}
          username: ${{ secrets.SWARM_USERNAME }}
          password: ${{ secrets.SWARM_PASSWORD }}
          script: |
            docker service update --image myapp:${{ github.sha }} myapp
